{% set version = "asp3.5.0" %} # synched up to isis dependencies for this version

package:
    name: s2p-subset
    version: {{ version }}

source:
  git_url: git@github.com:NeoGeographyToolkit/s2p.git
  # No tag, just use latest in HEAD  
  #  git_tag: afd6aa4 

build:
    number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - fftw 3.3.10
    - libpng 1.6.47
    - libtiff 4.6.0
    - openjpeg 2.5.2
    - zlib 1.3.1
    - zstd
 
  run:
    - fftw 3.3.10
    - libpng 1.6.47
    - libtiff 4.6.0
    - openjpeg 2.5.2
    - zlib 1.3.1
    - zstd
 
test:
    files:
        imports:
        commands:
        comment:

about:
    home:
    license: APACHE II
    summary: A subset algorithms from the S2P satellite processing package

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
